### ISSUE TITLE
The closing Double Quotation Marks on the "Add User via CMD" STAR Rule is missing

### ISSUE THREAD

**Issue by dannyroemhild** [acquiredsecurity/Sentinel-One-STAR-Rules-Threat-Hunts#2]
https://github.com/acquiredsecurity/Sentinel-One-STAR-Rules-Threat-Hunts/blob/main/STAR/Add%20User%20via%20CMD

When copy and pasting the query into the Visibility Hunting Console shows a corresponding note.

**Comment by acquiredsecurity** [comment]
Thanks updated!

**Comment by dannyroemhild** [comment]
Thanks
